local Bateman = require "DWAP_Bateman/configs/DWAP_Bateman"
print("DWAP Bateman extraLoot.lua loaded")
local extraLoot = {
    -- kitchen penthouse
    {
        type = 'container',
        coords = { x = 12776, y = 1534, z = 27 },
        dist = {"FridgeRich","FridgeVIPLounge" },
        distIncludeJunk = false,
        randUntilFull = true,
        frozen = true,
        level = "Loot_FoodLevel",
    },
    {
        type = 'container',
        coords = { x = 12777, y = 1532, z = 27 },
        dist = { "KitchenDryFood" },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_FoodLevel",
    },
    {
        type = 'container',
        coords = { x = 12777, y = 1532, z = 27.5 },
        dist = { "SeafoodKitchenSauce", "SpiffosKitchenSauce" },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_FoodLevel",
    },
    {
        type = 'container',
        coords = { x = 12779, y = 1532, z = 27 },
        dist = { "KitchenBreakfast" },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_FoodLevel",
    },
    {
        type = 'container',
        coords = { x = 12779, y = 1532, z = 27.5 },
        dist = { "ArenaKitchenSauce", "ArmyBunkerKitchen", "CrateButter" },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_FoodLevel",
    },
    -- penthouse lower
    {
        type = 'container',
        coords = { x = 12775, y = 1534, z = 26 },
        dist = { "FridgeVIPLounge", "DishCabinetVIPLounge" },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_FoodLevel",
    },
    -- penthouse lower bathroom
    {
        type = 'container',
        coords = { x = 12778, y = 1520, z = 26 },
        dist = { "LockerArmyBedroom", "LockerArmyBedroomHome", "CrateLinens" },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_LockersLevel",
    },
    {
        type = 'container',
        coords = { x = 12778, y = 1521, z = 26 },
            dist = {"SafehouseArmor", "SafehouseLighting"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
    },
    {
        type = 'container',
        coords = { x = 12778, y = 1522, z = 26 },
            dist = {"BathroomCounter", "GasStoreToiletries"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
    },
    {
        type = 'container',
        coords = { x = 12778, y = 1523, z = 26 },
            dist = {"GunStoreKnives", "SafehouseMedical"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_MedLevel",
    },
    -- 24th fl
    {
        type = 'container',
        coords = { x = 12761, y = 1524, z = 23 },
        dist = { "GardenStoreTools", "Homesteading", "ToolStoreFarming", "CrateFarming" },
        distIncludeJunk = false,
        randUntilFull = true,
        level = "Loot_FarmLevel",
    },
    {
        type = 'container',
        coords = { x = 12764, y = 1518, z = 23 },
        dist = { "ArmyStorageOutfit", "DrugLabOutfit", "LockerArmyBedroom", "LockerArmyBedroomHome", "ArmySurplusOutfit", "ToolStoreOutfit" },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_LockersLevel",
    },
    {
        type = 'container',
        coords = { x = 12765, y = 1518, z = 23 },
        dist = { "SewingStoreTools", "SewingStoreFabric" },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_TailorLevel",
    },
    -- bar on 22nd fl
    {
        type = 'container',
        coords = { x = 12777, y = 1524, z = 21 },
        dist = { "LiquorStoreWineFancy", "SafehouseBooze" },
        distIncludeJunk = false,
        randUntilFull = true,
        level = "Loot_FoodLevel",
    },
    {
        type = 'container',
        coords = { x = 12777, y = 1530, z = 21 },
        dist = { "LiquorStoreWineFancy", "BarCounterMisc" },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_FoodLevel",
    },
    {
        type = 'container',
        coords = { x = 12777, y = 1531, z = 21 },
        dist = { "BarCounterLiquor", "BarShelfLiquor" },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_FoodLevel",
    },
    -- 22nd kitchen
    {
        type = 'container',
        coords = { x = 12761, y = 1528, z = 21 },
        dist = {"StoreKitchenPotatoes", "CrateButter"},
        distIncludeJunk = false,
        randUntilFull = true,
        level = "Loot_FoodLevel",
    },
    {
        type = 'container',
        coords = { x = 12762, y = 1528, z = 21 },
        dist = { "StoreShelfDrinks", "FridgeSoda", "CrateSodaBottles" },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_FoodLevel",
    },
    {
        type = 'container',
        coords = { x = 12761, y = 1529, z = 21 },
        dist = { "KitchenDryFood" },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_FoodLevel",
    },
    {
        type = 'container',
        coords = { x = 12761, y = 1532, z = 21 },
        dist = { "MexicanKitchenSauce", "MexicanKitchenBaking", },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_FoodLevel",
    },
    {
        type = 'container',
        coords = { x = 12761, y = 1533, z = 21 },
        dist = { "PizzaKitchenBaking", "PizzaKitchenCheese", "PizzaKitchenSauce" },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_FoodLevel",
    },
    {
        type = 'container',
        coords = { x = 12765, y = 1533, z = 21 },
        dist = {"FreezerIceCream", "CafeteriaKitchenFreezer", },
        distIncludeJunk = false,
        randUntilFull = true,
        frozen = true,
        level = "Loot_FoodLevel",
    },
    -- 21st offices
    {
        type = 'container',
        coords = { x = 12766, y = 1530, z = 20 },
        dist = { "BurglarTools", "CarpenterTools", "BarnTools" },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_ToolsLevel",
    },
    {
        type = 'container',
        coords = { x = 12767, y = 1530, z = 20 },
        dist = { "GigamartTools", "JanitorTools" },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_ToolsLevel",
    },
    {
        type = 'container',
        coords = { x = 12772, y = 1530, z = 20 },
        dist = {"GigamartDryGoods", "CafeKitchenCoffee", "CafeKitchenSupplies", "CafeKitchenTea", "CrateSodaBottles"},
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_FoodLevel",
    },
    {
        type = 'container',
        coords = { x = 12769, y = 1523, z = 20 },
            dist = {"CrateTortillaChips",},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
    },
    -- 19
    {
        type = 'container',
        coords = { x = 12778, y = 1534, z = 18 },
        dist = {"GigamartDryGoods", "CafeKitchenCoffee", "CafeKitchenSupplies", "CafeKitchenTea", "CrateSodaBottles"},
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_FoodLevel",
    },
    -- 17
    {
        type = 'container',
        coords = { x = 12782, y = 1529, z = 16 },
        dist = {"GigamartDryGoods", "CafeKitchenCoffee", "CafeKitchenSupplies", "CafeKitchenTea", "CrateSodaBottles"},
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_FoodLevel",
    },
    {
        type = 'container',
        coords = { x = 12781, y = 1532, z = 16 },
        dist = { "CrateVHSTapes", "MovieRentalShelves" },
        distIncludeJunk = false,
        randUntilFull = true,
        level = "Loot_MediaLevel",
    },
    -- 15th
    {
        type = 'container',
        coords = { x = 12757, y = 1521, z = 14 },
        dist = {"GigamartDryGoods", "CafeKitchenCoffee", "CafeKitchenSupplies", "CafeKitchenTea", "CrateSodaBottles"},
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_FoodLevel",
    },
    {
        type = 'container',
        coords = { x = 12758, y = 1521, z = 14 },
        dist = { "CrepeKitchenBaking", "CrepeKitchenSauce" },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_FoodLevel",
    },
    {
        type = 'container',
        coords = { x = 12785, y = 1530, z = 14 },
        dist = {"FreezerIceCream", },
        distIncludeJunk = false,
        randUntilFull = true,
        frozen = true,
        level = "Loot_FoodLevel",
    },
    {
        type = 'container',
        coords = { x = 12785, y = 1531, z = 14 },
        dist = {"CafeteriaKitchenFreezer", },
        distIncludeJunk = false,
        randUntilFull = true,
        frozen = true,
        level = "Loot_FoodLevel",
    },
    {
        type = 'container',
        coords = { x = 12785, y = 1532, z = 14 },
        dist = {"WesternKitchenFridge"},
        distIncludeJunk = false,
        randUntilFull = true,
        frozen = true,
        level = "Loot_FoodLevel",
    },
    {
        type = 'container',
        coords = { x = 12781, y = 1535, z = 14 },
        dist = {"CrateCannedFood", "KitchenCannedFood"},
        distIncludeJunk = false,
        randUntilFull = true,
        level = "Loot_FoodLevel",
    },
    {
        type = 'container',
        coords = { x = 12781, y = 1538, z = 14 },
        dist = {"ButcherSpices","GigamartSpices","GroceryBagGourmet",},
        distIncludeJunk = false,
        randUntilFull = true,
        level = "Loot_FoodLevel",
    },
    {
        type = 'container',
        coords = { x = 12787, y = 1521, z = 14 },
        dist = {"MedicalClinicTools", "MedicalStorageDrugs","MedicalCabinet"},
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_MedLevel",
    },
    {
        type = 'container',
        coords = { x = 12787, y = 1522, z = 14 },
        dist = {"JanitorCleaning","MedicalCabinet","MedicalClinicDrugs", "CrateLinens"},
        distIncludeJunk = false,
        randUntilFull = true,
        level = "Loot_MedLevel",
    },
    -- 13th
    {
        type = 'container',
        coords = { x = 12782, y = 1540, z = 12 },
        dist = {"GigamartDryGoods", "CafeKitchenCoffee", "CafeKitchenSupplies", "CafeKitchenTea", "CrateSodaBottles"},
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_FoodLevel",
    },
    -- 11th
    {
        type = 'container',
        coords = { x = 12768, y = 1533, z = 11 },
        dist = { "GunStoreKnives", "PawnShopKnives", },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_GunLevel",
    },
    {
        type = 'container',
        coords = { x = 12768, y = 1534, z = 11 },
        dist = {"ArmyStorageGuns","ArmyStorageAmmunition","FirearmWeapons_Late"},
        distIncludeJunk = false,
        randUntilFull = true,
        level = "Loot_GunLevel",
    },
    {
        type = 'container',
        coords = { x = 12768, y = 1535, z = 11 },
        special = "gunlocker",
        level = "Loot_GunLevel",
    },
    {
        type = 'container',
        coords = { x = 12768, y = 1536, z = 11 },
        special = "gunlocker",
        level = "Loot_GunLevel",
    },
    -- 10th
    {
        type = 'container',
        coords = { x = 12778, y = 1534, z = 9 },
        dist = {"CrateAntiqueStove", "CampingStoreLighting"},
        distIncludeJunk = false,
        randUntilFull = true,
        level = 1,
    },
    {
        type = 'container',
        coords = { x = 12778, y = 1535, z = 9 },
        dist = { "CrateSheetMetal" },
        distIncludeJunk = false,
        randUntilFull = true,
        level = "Loot_BuildMatsLevel",
    },
    {
        type = 'container',
        coords = { x = 12778, y = 1536, z = 9 },
        dist = { "CrateLumber" },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_BuildMatsLevel",
    },
    {
        type = 'container',
        coords = { x = 12789, y = 1529, z = 9 },
        items = {
            { name = 'Base.NailsBox', },
            { name = 'Base.ScrewsBox', },
        },
        randUntilFull = true,
        level = "Loot_BuildMatsLevel",
    },
    {
        type = 'container',
        coords = { x = 12789, y = 1530, z = 9 },
        dist = {"ToolFactoryBarStock", "ToolFactoryHandles", "ArtStorePottery",},
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_BuildMatsLevel",
    },
    {
        type = 'container',
        coords = { x = 12754, y = 1517, z = 9 },
        dist = {"BarnTools", "CrateAnimalFeed", },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_FarmLevel",
    },
    {
        type = 'container',
        coords = { x = 12754, y = 1518, z = 9 },
        dist = {"SurvivalGear",},
        distIncludeJunk = false,
        randUntilFull = true,
        level = "Loot_LockersLevel",
    },
    {
        type = 'container',
        coords = { x = 12763, y = 1522, z = 9 },
            items = {
                { name = 'Base.AnimalFeedBag', chance = 1, count = {9,12} },
                { name = 'Base.Fertilizer', chance = 1, count = {8,10} },
            },
            randUntilFull = true,
            level = "Loot_FarmLevel",
    },
    {
        type = 'container',
        coords = { x = 12777, y = 1516, z = 9 },
        dist = {"CrateLumber", "CrateSheetMetal", "ToolFactoryBarStock", "ToolFactoryHandles", "WeldingWorkshopMetal","ToolFactoryIngots"},
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_BuildMatsLevel",
    },
    {
        type = 'container',
        coords = { x = 12776, y = 1516, z = 9 },
        dist = {"CrateLumber", "CrateSheetMetal", "ToolFactoryBarStock", "ToolFactoryHandles", "WeldingWorkshopMetal","ToolFactoryIngots"},
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_BuildMatsLevel",
    },
    {
        type = 'container',
        coords = { x = 12776, y = 1517, z = 9 },
        dist = {"CrateLumber", "CrateSheetMetal"},
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_BuildMatsLevel",
    },
    {
        type = 'container',
        coords = { x = 12776, y = 1518, z = 9 },
        dist = {"CrateLumber", "CrateSheetMetal"},
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_BuildMatsLevel",
    },
    -- 7th
    {
        type = 'container',
        coords = { x = 12781, y = 1533, z = 7 },
        dist = {"GigamartDryGoods", "CafeKitchenCoffee", "CafeKitchenSupplies", "CafeKitchenTea", "CrateSodaBottles"},
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_FoodLevel",
    },
    {
        type = 'container',
        coords = { x = 12761, y = 1526, z = 7 },
        dist = {"CrateBlacksmithing", "CrateCarpentry", "CrateMechanics", "CrateMetalwork" },
        distIncludeJunk = false,
        randUntilFull = true,
        level = "Loot_ToolsLevel",
    },
    {
        type = 'container',
        coords = { x = 12762, y = 1526, z = 7 },
        dist = {"TestingLab", "TobaccoStoreAccessories", "CandyStoreSnacks"},
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_FoodLevel",
    },
    -- 5th
    {
        type = 'container',
        coords = { x = 12781, y = 1533, z = 5 },
        dist = {"GigamartDryGoods", "CafeKitchenCoffee", "CafeKitchenSupplies", "CafeKitchenTea", "CrateSodaBottles"},
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_FoodLevel",
    },
    {
        type = 'container',
        coords = { x = 12761, y = 1526, z = 5 },
        dist = {"SewingStoreFabric","CrateLeather", "ArtSupplies"},
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_TailorLevel",
    },
    {
        type = 'container',
        coords = { x = 12762, y = 1526, z = 5 },
        dist = {"ArmyStorageElectronics", "RandomFiller" },
        distIncludeJunk = false,
        randUntilFull = true,
        level = "Loot_BuildMatsLevel",
    },
    -- 3rd
    {
        type = 'container',
        coords = { x = 12776, y = 1518, z = 3 },
        dist = {"JanitorCleaning","MedicalCabinet", "CrateLinens"},
        distIncludeJunk = false,
        randUntilFull = true,
        level = "Loot_MedLevel",
    },
    {
        type = 'container',
        coords = { x = 12777, y = 1518, z = 3 },
        dist = {"CrateToiletPaper", "CrateLinens","GasStoreToiletries"},
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_LockersLevel",
    },
    {
        type = 'container',
        coords = { x = 12769, y = 1530, z = 3 },
        dist = {"CrateTortillaChips",},
        distIncludeJunk = false,
        randUntilFull = true,
        level = "Loot_FoodLevel",
    },
    -- 0
    {
        type = 'container',
        coords = { x = 12783, y = 1520, z = 0 },
        dist = {"GigamartDryGoods", "CafeKitchenCoffee", "CafeKitchenSupplies", "CafeKitchenTea", "CrateSodaBottles"},
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_FoodLevel",
    },
    {
        type = 'container',
        coords = { x = 12762, y = 1527, z = 0 },
            dist = {"CrateCarpentry","LoggingFactoryTools"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
    },
    {
        type = 'container',
        coords = { x = 12763, y = 1527, z = 0 },
            dist = {"RadioFactoryComponents", "CrateElectronics", "ArmyStorageElectronics"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
    },
    {
        type = 'container',
        coords = { x = 12764, y = 1527, z = 0 },
            dist = {"ToolCabinetMechanics","CrateMechanics"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
    },
    {
        type = 'container',
        coords = { x = 12765, y = 1527, z = 0 },
            dist = {"RailYardTools","Homesteading","SurvivalGear"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
    },
    {
        type = 'container',
        coords = { x = 12766, y = 1527, z = 0 },
            dist = {"WireFactoryBarbed", "CrateLongStick", "WireFactoryBasic"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
    },
}

if Bateman and Bateman.loot then
    for i = 1, #extraLoot do
        table.insert(Bateman.loot, extraLoot[i])
    end
end

return Bateman
